apiVersion: 1

datasources:
  - name: Loki
    type: loki
    access: proxy
    url: http://loki:3100
    basicAuth: false
    isDefault: true
    version: 1
    editable: true
    uid: loki
    jsonData:
      maxLines: 1000
      timeout: 60s
      derivedFields:
        - name: "Trace ID"
          matcherRegex: "correlation_id=([\\w-]+)"
          url: "http://localhost:3000/explore?orgId=1&left=%5B%22now-1h%22,%22now%22,%22Tempo%22,%7B%22query%22:%22$${__value.raw}%22%7D%5D"
          datasourceUid: tempo

  - name: Tempo  
    type: tempo
    access: proxy
    url: http://tempo:3200
    basicAuth: false
    version: 1
    editable: true
    uid: tempo
    jsonData:
      httpMethod: GET
      tracesToLogs:
        datasourceUid: 'loki'
        tags: ['job', 'instance', 'correlation_id']
        mappedTags: [{ key: 'correlation_id', value: 'correlation_id' }]
        mapTagNamesEnabled: true
        spanStartTimeShift: '1h'
        spanEndTimeShift: '1h'
        filterByTraceID: false
        filterBySpanID: false
        lokiSearch: true