version: '3.8'

services:
  # NATS with JetStream
  nats:
    image: nats:latest
    container_name: concordance-nats
    ports:
      - "4222:4222"
      - "8222:8222"
    command: "--js"
    volumes:
      - type: volume
        source: nats-data
        target: /data
    networks:
      - concordance-net
    restart: unless-stopped

  # Jaeger All-in-One
  jaeger:
    image: jaegertracing/all-in-one:1.51
    container_name: concordance-jaeger
    ports:
      - "16686:16686"  # Jaeger UI
      - "14250:14250"  # Jaeger gRPC
      - "14268:14268"  # Jaeger HTTP Thrift
      - "4317:4317"    # OTLP gRPC receiver
      # - "4318:4318"    # OTLP HTTP receiver
    environment:
      - COLLECTOR_OTLP_ENABLED=true
      - LOG_LEVEL=debug
    volumes:
      - jaeger-data:/tmp
    networks:
      - concordance-net
    restart: unless-stopped

  # OpenTelemetry Collector (optional - for advanced routing)
  otel-collector:
    image: otel/opentelemetry-collector-contrib:0.91.0
    container_name: concordance-otel-collector
    command: ["--config=/etc/otel-collector-config.yaml"]
    volumes:
      - ./otel-collector-config.yaml:/etc/otel-collector-config.yaml:ro
    ports:
      # - "4317:4317"    # OTLP gRPC receiver
      - "4318:4318"    # OTLP HTTP receiver
      - "8888:8888"    # Metrics endpoint
      - "13133:13133"  # Health check
    depends_on:
      - jaeger
    networks:
      - concordance-net
    restart: unless-stopped

networks:
  concordance-net:
    driver: bridge

volumes:
  nats-data:
  jaeger-data: